// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1raWhRoipMTPX1VpNkUeCihDajk10ew',
    appId: '1:495493798997:web:b474828b6724b761ad88dc',
    messagingSenderId: '495493798997',
    projectId: 'englishapp-bd9eb',
    authDomain: 'englishapp-bd9eb.firebaseapp.com',
    storageBucket: 'englishapp-bd9eb.firebasestorage.app',
    measurementId: 'G-S976BY5Y3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauzRv40YYrZ40Hk2bNm89hVB2jgccLyI',
    appId: '1:495493798997:android:e6a14347842735b0ad88dc',
    messagingSenderId: '495493798997',
    projectId: 'englishapp-bd9eb',
    storageBucket: 'englishapp-bd9eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ib5PSaa1n8Qb0lgJJGXava873acwjo8',
    appId: '1:495493798997:ios:c39dacc282a4f593ad88dc',
    messagingSenderId: '495493798997',
    projectId: 'englishapp-bd9eb',
    storageBucket: 'englishapp-bd9eb.firebasestorage.app',
    iosClientId: '495493798997-vbom122vs0d4qt7mvjtome3lsl7p9jv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ib5PSaa1n8Qb0lgJJGXava873acwjo8',
    appId: '1:495493798997:ios:c39dacc282a4f593ad88dc',
    messagingSenderId: '495493798997',
    projectId: 'englishapp-bd9eb',
    storageBucket: 'englishapp-bd9eb.firebasestorage.app',
    iosClientId: '495493798997-vbom122vs0d4qt7mvjtome3lsl7p9jv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD1raWhRoipMTPX1VpNkUeCihDajk10ew',
    appId: '1:495493798997:web:8426f2b05a57be02ad88dc',
    messagingSenderId: '495493798997',
    projectId: 'englishapp-bd9eb',
    authDomain: 'englishapp-bd9eb.firebaseapp.com',
    storageBucket: 'englishapp-bd9eb.firebasestorage.app',
    measurementId: 'G-8TF4XBEQ0M',
  );
}
